namespace Viamus.Doxie.Orchestrator.Agents;

/// <summary>
/// Filesystem locations DoxieOS uses at runtime. Exposed via the
/// <c>Storage</c> section of <c>appsettings.json</c> so a deployed copy
/// can point at a different project root, a per-user state.db, etc.
///
/// **Path resolution**: relative paths are resolved against the
/// process's current directory at startup (typically the project root
/// where DoxieOS is launched). Use <see cref="ResolvePath"/> on each
/// directory before touching disk so renaming the root folder doesn't
/// break anything as long as the orchestrator is launched from the
/// new location.
/// </summary>
public sealed class StorageOptions
{
    /// <summary>
    /// Directory holding skill definitions. Each subdirectory contains a
    /// <c>manifest.json</c> + <c>body.md</c> pair and optional companion
    /// files (subcommand <c>*.md</c>, scripts, refs). Default is the
    /// canonical <c>.doxie/skills/</c>; the Claude Code shim under
    /// <c>.claude/skills/</c> is auto-generated on every save and is NOT
    /// read by the orchestrator at runtime.
    /// </summary>
    public string SkillsDirectory { get; set; } = ".doxie/skills";

    /// <summary>
    /// Directory holding Claude subagent definitions — single markdown
    /// files (<c>&lt;id&gt;.md</c>) with YAML frontmatter that declares
    /// the subagent's tools and behaviour. Often paired one-to-one with
    /// a skill of the same id (the skill orchestrates the subagent via
    /// the Task tool). Default is the canonical <c>.doxie/agents/</c>;
    /// the Claude shim at <c>.claude/agents/</c> is auto-generated.
    /// </summary>
    public string AgentsDirectory { get; set; } = ".doxie/agents";

    /// <summary>
    /// Full path to the SQLite database that persists run history and
    /// streamed output lines. The placeholder <c>%LOCALAPPDATA%</c> is
    /// resolved cross-platform by <see cref="ResolvePath"/>: on Windows
    /// it expands to <c>C:\Users\&lt;you&gt;\AppData\Local</c>, on Linux
    /// to <c>$XDG_DATA_HOME</c> (or <c>~/.local/share</c>), and on macOS
    /// to <c>~/Library/Application Support</c>. Override with an absolute
    /// path in appsettings if you want the data somewhere else.
    /// </summary>
    public string DatabasePath { get; set; } = "%LOCALAPPDATA%/Viamus.Doxie.Orchestrator/state.db";

    /// <summary>
    /// Directory holding DoxieOS libraries — reusable memory packs that
    /// can be loaded into a workspace at init time. Each subdirectory is
    /// one library, containing N memory <c>.md</c> files and an optional
    /// <c>library.json</c> manifest. Default is the canonical
    /// <c>.doxie/libraries/</c>; the <c>.claude/libraries/</c> copy is
    /// auto-generated by the regen pipeline and not read at runtime.
    /// </summary>
    public string LibrariesDirectory { get; set; } = ".doxie/libraries";

    /// <summary>
    /// Directory holding user-owned Workspaces — persistent project
    /// folders the user creates explicitly and can mount libraries into.
    /// Each subdirectory is one Workspace with a <c>workspace.json</c>
    /// manifest, a <c>WORKSPACE.md</c> readme, and a <c>memory/</c>
    /// folder. Distinct from <c>./.sandbox/</c> (which is agent-owned
    /// and transient). Default <c>./.workspace/</c> mirrors the
    /// <c>.sample-watch/</c>-style hidden dot-folder convention so the
    /// project root stays visually tidy.
    /// </summary>
    public string WorkspacesDirectory { get; set; } = ".workspace";

    /// <summary>
    /// Directory holding workflow definitions — compositions of agents
    /// connected by a graph plus a trigger. Each subdirectory is one
    /// workflow with a <c>workflow.json</c> manifest. Default
    /// <c>.doxie/workflows/</c> sits inside the canonical authoring
    /// layer alongside skills/agents/libraries — workflows are
    /// provider-neutral too, so they belong here rather than at the
    /// project root.
    /// </summary>
    public string WorkflowsDirectory { get; set; } = ".doxie/workflows";

    /// <summary>
    /// Directory holding per-run scratch folders for workflow execution.
    /// Each run gets its own subdirectory; each node inside that run gets
    /// a sub-subdirectory. Agents are pointed at their node directory via
    /// the <c>DOXIE_WORKFLOW_OUTPUT_DIR</c> env var; downstream
    /// <c>aggregate</c> nodes consume the union of upstream node dirs via
    /// <c>DOXIE_WORKFLOW_INPUT_DIRS</c> (semicolon-separated). Default
    /// <c>./.runs/</c> mirrors the dot-folder convention used by
    /// <c>.workspace/</c>, <c>.doxie/workflows/</c>, and <c>.sandbox/</c>.
    /// </summary>
    public string WorkflowRunsDirectory { get; set; } = ".runs";

    /// <summary>
    /// Directory holding per-standalone-run sandboxes — one subdirectory
    /// per agent invocation that ran outside a workflow. Agents allocate
    /// these themselves at <c>./.sandbox/&lt;agent&gt;-&lt;timestamp&gt;/</c> and
    /// write their artefacts there. Distinct from
    /// <c>WorkflowRunsDirectory</c> (which is workflow-runner-managed)
    /// and from user-owned <c>WorkspacesDirectory</c> (which is
    /// persistent and explicit). Cleaned by the housekeeping pass on
    /// the same retention as <c>.runs/</c>.
    /// </summary>
    public string SandboxesDirectory { get; set; } = ".sandbox";

    /// <summary>
    /// Resolves a configured path: expands <c>%VAR%</c> environment
    /// variables (with cross-platform handling for <c>%LOCALAPPDATA%</c>
    /// and <c>%USERPROFILE%</c>, which <see cref="System.Environment.ExpandEnvironmentVariables"/>
    /// only knows how to expand on Windows), then anchors a relative
    /// result against the project root (located by walking up from the
    /// process's CWD looking for a <c>.claude/</c> marker; falls back to
    /// CWD if none is found). This means DoxieOS works whether it's
    /// launched from the project root, from <c>bin/Debug/</c> (Visual
    /// Studio's default), or from anywhere inside the project tree.
    /// </summary>
    public static string ResolvePath(string configured)
    {
        var prepared = ExpandWellKnownTokens(configured);
        var expanded = System.Environment.ExpandEnvironmentVariables(prepared);
        if (System.IO.Path.IsPathRooted(expanded))
        {
            return expanded;
        }
        var root = ProjectRoot.Value;
        return System.IO.Path.GetFullPath(System.IO.Path.Combine(root, expanded));
    }

    /// <summary>
    /// Translates Windows-style placeholders into <see cref="System.Environment.SpecialFolder"/>
    /// paths so the same appsettings.json works on Linux/macOS without
    /// editing. <c>%LOCALAPPDATA%</c> â†’ <c>SpecialFolder.LocalApplicationData</c>
    /// (which is <c>~/.local/share</c> on Linux and <c>~/Library/Application
    /// Support</c> on macOS). <c>%USERPROFILE%</c> â†’ <c>SpecialFolder.UserProfile</c>
    /// (which is <c>$HOME</c> on POSIX).
    /// </summary>
    private static string ExpandWellKnownTokens(string configured)
    {
        if (string.IsNullOrEmpty(configured)) return configured;
        if (System.OperatingSystem.IsWindows()) return configured; // ExpandEnvironmentVariables handles these natively

        var localAppData = System.Environment.GetFolderPath(System.Environment.SpecialFolder.LocalApplicationData);
        var userProfile = System.Environment.GetFolderPath(System.Environment.SpecialFolder.UserProfile);

        return configured
            .Replace("%LOCALAPPDATA%", localAppData, System.StringComparison.OrdinalIgnoreCase)
            .Replace("%USERPROFILE%", userProfile, System.StringComparison.OrdinalIgnoreCase);
    }

    private static readonly Lazy<string> ProjectRoot = new(FindProjectRoot);

    private static string FindProjectRoot()
    {
        // Walk up from CWD looking for either marker:
        //   .doxie/  — canonical workspace folder (committed to git)
        //   .claude/ — provider shim (may be gitignored on fresh clones)
        // Either marker identifies a DoxieOS project root. Falls back to
        // CWD if neither is found (preserves the simpler behaviour for
        // environments without a workspace).
        var current = System.IO.Directory.GetCurrentDirectory();
        var probe = new System.IO.DirectoryInfo(current);
        while (probe is not null)
        {
            if (System.IO.Directory.Exists(System.IO.Path.Combine(probe.FullName, ".doxie")) ||
                System.IO.Directory.Exists(System.IO.Path.Combine(probe.FullName, ".claude")))
            {
                return probe.FullName;
            }
            probe = probe.Parent;
        }
        return current;
    }
}
