using System.Text.Json;
using Viamus.Doxie.Orchestrator.Common;

namespace Viamus.Doxie.Orchestrator.Context;

/// <summary>
/// User-owned Workspaces persisted under <c>./.workspace/&lt;id&gt;/</c>.
/// Each workspace folder carries a <c>workspace.json</c> manifest with
/// display metadata + mounted-library ids; absent or malformed manifest
/// degrades gracefully (folder name is used as both id and display name,
/// description empty, no mounted libraries).
/// </summary>
public sealed class FilesystemWorkspaceStore : IWorkspaceStore
{
    private const string ClaudeMdFileName = "CLAUDE.md";
    private const string CodexMdFileName = "AGENTS.md";
    // Marker used to identify context files the store wrote itself, so we
    // don't trample one a user hand-edited. If a workspace context file
    // exists without this header, mount changes leave it alone.
    private const string AutoGeneratedHeader = "<!-- DoxieOS: auto-generated from workspace.json mountedLibraries — edits will be overwritten when libraries change -->";

    private readonly string _directory;
    private readonly string _librariesDirectory;
    private readonly Func<IReadOnlyList<DoxieCatalogRoot>>? _catalogRootsProvider;

    public FilesystemWorkspaceStore(string directory, string librariesDirectory, Func<IReadOnlyList<DoxieCatalogRoot>>? catalogRootsProvider = null)
    {
        _directory = directory;
        _librariesDirectory = librariesDirectory;
        _catalogRootsProvider = catalogRootsProvider;
    }

    public IReadOnlyList<Workspace> ListAll()
    {
        var workspaces = new Dictionary<string, Workspace>(StringComparer.OrdinalIgnoreCase);
        foreach (var root in WorkspaceRoots())
        {
            if (!Directory.Exists(root)) continue;

            foreach (var dir in Directory.EnumerateDirectories(root))
            {
                var ws = TryLoad(dir);
                if (ws is not null) workspaces[ws.Id] = ws;
            }
        }
        return workspaces.Values
            .OrderBy(w => w.Name, StringComparer.OrdinalIgnoreCase)
            .ToList();
    }

    public Workspace? GetById(string id)
    {
        foreach (var root in WorkspaceRoots())
        {
            var dir = Path.Combine(root, id);
            if (Directory.Exists(dir)) return TryLoad(dir);
        }

        return null;
    }

    public Workspace Create(
        string id,
        string? displayName,
        string? description,
        IReadOnlyList<string>? mountedLibraryIds = null,
        IReadOnlyList<string>? mountedAgentIds = null)
    {
        var targetRoot = _directory;
        Directory.CreateDirectory(targetRoot);

        var dir = Path.Combine(targetRoot, id);
        if (WorkspaceRoots().Select(root => Path.Combine(root, id)).Any(Directory.Exists))
        {
            throw new InvalidOperationException($"Workspace '{id}' already exists.");
        }

        Directory.CreateDirectory(dir);
        Directory.CreateDirectory(Path.Combine(dir, "memory"));

        var resolvedName = !string.IsNullOrWhiteSpace(displayName) ? displayName!.Trim() : ToDisplayName(id);
        var resolvedDescription = description?.Trim() ?? string.Empty;
        var createdAt = DateTime.UtcNow;
        var deduped = (mountedLibraryIds ?? Array.Empty<string>())
            .Where(x => !string.IsNullOrWhiteSpace(x))
            .Select(x => x.Trim())
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToList();
        var dedupedAgents = (mountedAgentIds ?? Array.Empty<string>())
            .Where(x => !string.IsNullOrWhiteSpace(x))
            .Select(x => x.Trim())
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToList();

        var manifest = new WorkspaceManifest
        {
            Name = resolvedName,
            Description = resolvedDescription,
            CreatedAt = createdAt,
            MountedLibraries = deduped,
            MountedAgents = dedupedAgents,
        };
        File.WriteAllText(
            Path.Combine(dir, "workspace.json"),
            JsonSerializer.Serialize(manifest, new JsonSerializerOptions { WriteIndented = true }));

        File.WriteAllText(Path.Combine(dir, "WORKSPACE.md"),
            $"""
             # Workspace {resolvedName}

             **Id:** {id}
             **Created:** {createdAt:yyyy-MM-dd}
             {(string.IsNullOrEmpty(resolvedDescription) ? string.Empty : $"**Description:** {resolvedDescription}\n")}
             ## Mounted libraries
             _(none yet — set via the Workspaces page)_

             ## Notes
             _(your project notes go here; agents dispatched at this workspace can also write here)_
             """);

        File.WriteAllText(Path.Combine(dir, "memory", "MEMORY.md"),
            $"""
             # Workspace {resolvedName} — local memory index

             _(workspace-scoped persistent memory; lives alongside any libraries mounted into this workspace)_
             """);

        WriteContextFiles(dir, resolvedName, deduped);

        return new Workspace(
            Id: id,
            Name: resolvedName,
            Description: resolvedDescription,
            CreatedAt: createdAt,
            MountedLibraryIds: deduped,
            Path: dir)
        {
            MountedAgentIds = dedupedAgents,
        };
    }

    public void Delete(string id)
    {
        var dir = FindWorkspaceDir(id);
        if (dir is null || !Directory.Exists(dir))
        {
            throw new InvalidOperationException($"Workspace '{id}' not found.");
        }
        Directory.Delete(dir, recursive: true);
    }

    public Workspace SetMountedLibraries(string id, IReadOnlyList<string> libraryIds)
    {
        var dir = FindWorkspaceDir(id);
        if (dir is null || !Directory.Exists(dir))
        {
            throw new InvalidOperationException($"Workspace '{id}' not found.");
        }

        // Dedupe + preserve user-supplied ordering. Caller is responsible
        // for kebab-case validation; this method writes whatever it's
        // given so it can stay agnostic about library-id rules.
        var deduped = libraryIds
            .Where(x => !string.IsNullOrWhiteSpace(x))
            .Select(x => x.Trim())
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToList();

        var existing = LoadManifest(dir) ?? new WorkspaceManifest();
        existing.MountedLibraries = deduped;
        // CreatedAt is preserved from the existing manifest; if the
        // manifest was missing for some reason, fall back to the dir's
        // creation time so we don't bump the workspace's "age" on every
        // mount edit.
        existing.CreatedAt ??= Directory.GetCreationTimeUtc(dir);
        existing.Name ??= ToDisplayName(id);
        existing.Description ??= string.Empty;

        File.WriteAllText(
            Path.Combine(dir, "workspace.json"),
            JsonSerializer.Serialize(existing, new JsonSerializerOptions { WriteIndented = true }));

        WriteContextFiles(dir, existing.Name!, deduped);

        return new Workspace(
            Id: id,
            Name: existing.Name!,
            Description: existing.Description!,
            CreatedAt: existing.CreatedAt!.Value,
            MountedLibraryIds: deduped,
            Path: dir)
        {
            MountedAgentIds = existing.MountedAgents ?? new List<string>(),
        };
    }

    public Workspace SetMountedAgents(string id, IReadOnlyList<string> agentIds)
    {
        var dir = FindWorkspaceDir(id);
        if (dir is null || !Directory.Exists(dir))
        {
            throw new InvalidOperationException($"Workspace '{id}' not found.");
        }

        var deduped = agentIds
            .Where(x => !string.IsNullOrWhiteSpace(x))
            .Select(x => x.Trim())
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToList();

        var existing = LoadManifest(dir) ?? new WorkspaceManifest();
        existing.MountedAgents = deduped;
        existing.CreatedAt ??= Directory.GetCreationTimeUtc(dir);
        existing.Name ??= ToDisplayName(id);
        existing.Description ??= string.Empty;
        existing.MountedLibraries ??= new List<string>();

        File.WriteAllText(
            Path.Combine(dir, "workspace.json"),
            JsonSerializer.Serialize(existing, new JsonSerializerOptions { WriteIndented = true }));

        return new Workspace(
            Id: id,
            Name: existing.Name!,
            Description: existing.Description!,
            CreatedAt: existing.CreatedAt!.Value,
            MountedLibraryIds: existing.MountedLibraries,
            Path: dir)
        {
            MountedAgentIds = deduped,
        };
    }

    private void WriteContextFiles(string workspaceDir, string workspaceName, IReadOnlyList<string> mountedLibraryIds)
    {
        WriteClaudeMd(workspaceDir, workspaceName, mountedLibraryIds);
        WriteAgentsMd(workspaceDir, workspaceName, mountedLibraryIds);
    }

    private string? FindWorkspaceDir(string id) =>
        WorkspaceRoots()
            .Select(root => Path.Combine(root, id))
            .FirstOrDefault(Directory.Exists);

    private IEnumerable<string> WorkspaceRoots()
    {
        yield return _directory;
    }

    /// <summary>
    /// Writes (or rewrites) the workspace's <c>CLAUDE.md</c> with
    /// <c>@</c>-import lines for every mounted library memory. Claude
    /// Code inlines those at session start, so the libraries' memories
    /// become part of the workspace instructions without copying them.
    /// </summary>
    private void WriteClaudeMd(string workspaceDir, string workspaceName, IReadOnlyList<string> mountedLibraryIds)
    {
        var claudeMdPath = Path.Combine(workspaceDir, ClaudeMdFileName);
        if (!CanOverwriteGeneratedFile(claudeMdPath)) return;

        if (mountedLibraryIds.Count == 0)
        {
            DeleteGeneratedFile(claudeMdPath);
            return;
        }

        var sb = new System.Text.StringBuilder();
        sb.AppendLine(AutoGeneratedHeader);
        sb.AppendLine();
        sb.AppendLine($"# {workspaceName} — workspace context");
        sb.AppendLine();
        sb.AppendLine("This workspace mounts the following DoxieOS libraries. Their memory files are inlined below via `@` imports — Claude reads each one as part of this session's project instructions.");
        sb.AppendLine();

        foreach (var libId in mountedLibraryIds)
        {
            var libDir = FindLibraryDir(libId);
            sb.AppendLine($"## {libId}");
            sb.AppendLine();
            if (libDir is null || !Directory.Exists(libDir))
            {
                sb.AppendLine($"_Library `{libId}` not found in any configured catalog — mount is stale; remove or recreate via the Libraries page._");
                sb.AppendLine();
                continue;
            }

            var mdFiles = EnumerateLibraryMemoryFiles(libDir);
            if (mdFiles.Count == 0)
            {
                sb.AppendLine("_(library has no memory files yet)_");
                sb.AppendLine();
                continue;
            }

            foreach (var file in mdFiles)
            {
                // Relative path from the workspace dir to the library
                // file. Claude resolves @ imports relative to CLAUDE.md.
                var rel = Path.GetRelativePath(workspaceDir, file).Replace('\\', '/');
                sb.AppendLine($"@{rel}");
            }
            sb.AppendLine();
        }

        try { File.WriteAllText(claudeMdPath, sb.ToString()); }
        catch (IOException) { /* best-effort; surface via UI later */ }
    }

    /// <summary>
    /// Writes (or rewrites) the workspace's <c>AGENTS.md</c> for Codex.
    /// Codex does not resolve Claude-style <c>@</c> imports, so the same
    /// mounted memory files are embedded directly.
    /// </summary>
    private void WriteAgentsMd(string workspaceDir, string workspaceName, IReadOnlyList<string> mountedLibraryIds)
    {
        var agentsMdPath = Path.Combine(workspaceDir, CodexMdFileName);
        if (!CanOverwriteGeneratedFile(agentsMdPath)) return;

        if (mountedLibraryIds.Count == 0)
        {
            DeleteGeneratedFile(agentsMdPath);
            return;
        }

        var sb = new System.Text.StringBuilder();
        sb.AppendLine(AutoGeneratedHeader);
        sb.AppendLine();
        sb.AppendLine($"# {workspaceName} - workspace context");
        sb.AppendLine();
        sb.AppendLine("This workspace mounts DoxieOS libraries. Codex reads AGENTS.md directly, so the memory files are embedded below.");
        sb.AppendLine();

        foreach (var libId in mountedLibraryIds)
        {
            var libDir = FindLibraryDir(libId);
            sb.AppendLine($"## Library: {libId}");
            sb.AppendLine();
            if (libDir is null || !Directory.Exists(libDir))
            {
                sb.AppendLine($"Library `{libId}` was not found in any configured catalog. The mount is stale; remove or recreate it via the Libraries page.");
                sb.AppendLine();
                continue;
            }

            var mdFiles = EnumerateLibraryMemoryFiles(libDir);
            if (mdFiles.Count == 0)
            {
                sb.AppendLine("This library has no memory files yet.");
                sb.AppendLine();
                continue;
            }

            foreach (var file in mdFiles)
            {
                var rel = Path.GetRelativePath(libDir, file).Replace('\\', '/');
                sb.AppendLine($"### {rel}");
                sb.AppendLine();
                try
                {
                    sb.AppendLine(File.ReadAllText(file).TrimEnd());
                }
                catch (IOException ex)
                {
                    sb.AppendLine($"Could not read `{rel}`: {ex.Message}");
                }
                sb.AppendLine();
            }
        }

        try { File.WriteAllText(agentsMdPath, sb.ToString()); }
        catch (IOException) { /* best-effort; surface via UI later */ }
    }

    private static bool CanOverwriteGeneratedFile(string path)
    {
        if (!File.Exists(path)) return true;
        try
        {
            var first = File.ReadLines(path).FirstOrDefault() ?? string.Empty;
            return first.Contains("DoxieOS: auto-generated");
        }
        catch (IOException)
        {
            return true;
        }
    }

    private static void DeleteGeneratedFile(string path)
    {
        try { if (File.Exists(path)) File.Delete(path); }
        catch (IOException) { /* best-effort */ }
    }

    private string? FindLibraryDir(string id) =>
        LibraryRoots()
            .Select(root => Path.Combine(root, id))
            .FirstOrDefault(Directory.Exists);

    private IEnumerable<string> LibraryRoots()
    {
        if (_catalogRootsProvider is not null)
        {
            foreach (var root in _catalogRootsProvider())
            {
                yield return root.LibrariesDirectory;
            }
            yield break;
        }

        yield return _librariesDirectory;
    }

    private static IReadOnlyList<string> EnumerateLibraryMemoryFiles(string libDir)
    {
        var files = new List<string>();
        files.AddRange(Directory.EnumerateFiles(libDir, "*.md", SearchOption.TopDirectoryOnly));

        var memoryDir = Path.Combine(libDir, "memory");
        if (Directory.Exists(memoryDir))
        {
            files.AddRange(Directory.EnumerateFiles(memoryDir, "*.md", SearchOption.AllDirectories));
        }

        return files
            .Where(IsMemoryFile)
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(f => Path.GetRelativePath(libDir, f).Replace('\\', '/'), StringComparer.OrdinalIgnoreCase)
            .ToList();
    }

    private static bool IsMemoryFile(string file)
    {
        var fileName = Path.GetFileName(file);
        return !string.Equals(fileName, "MEMORY.md", StringComparison.OrdinalIgnoreCase)
            && !string.Equals(fileName, "README.md", StringComparison.OrdinalIgnoreCase);
    }

    private static Workspace? TryLoad(string dir)
    {
        var id = Path.GetFileName(dir);
        if (string.IsNullOrEmpty(id)) return null;

        var manifest = LoadManifest(dir);
        var name = !string.IsNullOrWhiteSpace(manifest?.Name) ? manifest!.Name! : ToDisplayName(id);
        var description = manifest?.Description ?? string.Empty;
        var createdAt = manifest?.CreatedAt ?? Directory.GetCreationTimeUtc(dir);
        var mounted = (IReadOnlyList<string>)(manifest?.MountedLibraries ?? new List<string>());
        var mountedAgents = (IReadOnlyList<string>)(manifest?.MountedAgents ?? new List<string>());

        return new Workspace(
            Id: id,
            Name: name,
            Description: description,
            CreatedAt: createdAt,
            MountedLibraryIds: mounted,
            Path: dir)
        {
            MountedAgentIds = mountedAgents,
        };
    }

    private static WorkspaceManifest? LoadManifest(string dir)
    {
        var path = Path.Combine(dir, "workspace.json");
        if (!File.Exists(path)) return null;
        try
        {
            return JsonSerializer.Deserialize<WorkspaceManifest>(
                File.ReadAllText(path),
                new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
        }
        catch (JsonException) { return null; }
    }

    private static string ToDisplayName(string identifier) =>
        string.Join(" ", identifier
            .Split(['-', '_'], StringSplitOptions.RemoveEmptyEntries)
            .Select(p => p.Length == 0 ? string.Empty : char.ToUpperInvariant(p[0]) + p[1..]));

    private sealed class WorkspaceManifest
    {
        public string? Name { get; set; }
        public string? Description { get; set; }
        public DateTime? CreatedAt { get; set; }
        public List<string>? MountedLibraries { get; set; }
        public List<string>? MountedAgents { get; set; }
    }
}
