using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Viamus.Doxie.Orchestrator.Agents.Doxie;

/// <summary>
/// Emits the Claude Code shim under <c>.claude/skills/&lt;id&gt;/</c> from
/// canonical skills. Each skill becomes:
/// <list type="bullet">
/// <item><c>SKILL.md</c> — YAML frontmatter (<c>name</c>, <c>description</c>) + body markdown</item>
/// <item><c>orchestrator.json</c> — projection of manifest minus the parts that
///       belong in the frontmatter</item>
/// <item>Companion files (subcommand <c>*.md</c>, scripts/, refs) copied verbatim</item>
/// </list>
///
/// Idempotent. Writes are content-aware — files are only rewritten when bytes
/// differ, so running the emitter doesn't churn timestamps or fire watchers
/// downstream. Orphan files inside skill folders that disappear from the
/// canonical set are deleted; folders for unknown skills (those the orchestrator
/// didn't generate) are left alone.
/// </summary>
public sealed class ClaudeShimEmitter : IShimEmitter
{
    private const string GeneratedMarker = "doxie/generated";

    private static readonly JsonSerializerOptions OrchestratorJsonOptions = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        WriteIndented = true,
        Converters = { new JsonStringEnumConverter() },
    };

    public string ShimRoot => ".claude/skills";

    public void Emit(DoxieRegistry registry, string workspaceRoot)
    {
        var skillsRoot = Path.Combine(workspaceRoot, ".claude", "skills");
        Directory.CreateDirectory(skillsRoot);

        var managedFolders = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var skill in registry.Skills)
        {
            EmitOne(skill, skillsRoot);
            managedFolders.Add(skill.Manifest.Id);
        }

        // Orphan cleanup is gated on the marker file: only delete folders we
        // own (have a .doxie-generated marker) but no longer have a canonical
        // entry for. User-authored skills under .claude/skills/ are untouched.
        foreach (var dir in Directory.EnumerateDirectories(skillsRoot))
        {
            var name = Path.GetFileName(dir);
            if (managedFolders.Contains(name)) continue;
            if (!File.Exists(Path.Combine(dir, GeneratedMarker))) continue;
            Directory.Delete(dir, recursive: true);
        }
    }

    private static void EmitOne(DoxieSkillCanon skill, string skillsRoot)
    {
        var dir = Path.Combine(skillsRoot, skill.Manifest.Id);
        Directory.CreateDirectory(dir);

        var skillMdBytes = Encoding.UTF8.GetBytes(BuildSkillMd(skill));
        WriteIfChanged(Path.Combine(dir, "SKILL.md"), skillMdBytes);

        var orchestratorBytes = BuildOrchestratorJsonBytes(skill);
        if (orchestratorBytes is not null)
        {
            WriteIfChanged(Path.Combine(dir, "orchestrator.json"), orchestratorBytes);
        }
        else
        {
            // Manifest had no orchestrator-side metadata — drop a stale sidecar
            // from a previous regen if one exists.
            var orchestratorPath = Path.Combine(dir, "orchestrator.json");
            if (File.Exists(orchestratorPath)) File.Delete(orchestratorPath);
        }

        // Companion files keep their relative paths inside the skill folder.
        var expectedCompanions = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var (relPath, content) in skill.CompanionFiles)
        {
            var fullPath = Path.Combine(dir, relPath.Replace('/', Path.DirectorySeparatorChar));
            Directory.CreateDirectory(Path.GetDirectoryName(fullPath)!);
            WriteIfChanged(fullPath, content);
            expectedCompanions.Add(NormalizeRel(relPath));
        }

        // Stamp the generated-by marker so future regen knows this folder is
        // ours to manage. Marker doubles as an opt-in flag for orphan deletion.
        WriteIfChanged(
            Path.Combine(dir, GeneratedMarker),
            Encoding.UTF8.GetBytes($"# Generated by DoxieOS from .doxie/skills/{skill.Manifest.Id}/"));

        // Delete companion files that disappeared from the canon. Skips
        // SKILL.md, orchestrator.json, and the marker (managed above).
        DeleteOrphanCompanions(dir, expectedCompanions);
    }

    private static void DeleteOrphanCompanions(string skillDir, HashSet<string> expected)
    {
        foreach (var file in Directory.EnumerateFiles(skillDir, "*", SearchOption.AllDirectories))
        {
            var rel = NormalizeRel(Path.GetRelativePath(skillDir, file));
            if (rel.Equals("SKILL.md", StringComparison.OrdinalIgnoreCase)) continue;
            if (rel.Equals("orchestrator.json", StringComparison.OrdinalIgnoreCase)) continue;
            if (rel.Equals(GeneratedMarker, StringComparison.OrdinalIgnoreCase)) continue;
            if (expected.Contains(rel)) continue;
            File.Delete(file);
        }
        // Sweep empty directories left behind by deletes.
        foreach (var subDir in Directory.EnumerateDirectories(skillDir, "*", SearchOption.AllDirectories)
            .OrderByDescending(d => d.Length))
        {
            if (!Directory.EnumerateFileSystemEntries(subDir).Any())
            {
                Directory.Delete(subDir);
            }
        }
    }

    private static string NormalizeRel(string rel) => rel.Replace('\\', '/');

    private static string BuildSkillMd(DoxieSkillCanon skill)
    {
        // Frontmatter holds the two fields Claude Code itself reads from
        // SKILL.md — name (the slash command) and description (used to
        // decide skill relevance). Everything else lives in orchestrator.json.
        // Description is single-line; multi-line descriptions in the canon
        // are flattened with spaces because the Claude parser reads the
        // value as one line after the colon.
        var sb = new StringBuilder();
        sb.Append("---\n");
        sb.Append("name: ").Append(skill.Manifest.Id).Append('\n');
        sb.Append("description: ").Append(FlattenForFrontmatter(skill.Manifest.Description)).Append('\n');
        sb.Append("---\n\n");
        sb.Append(skill.BodyMarkdown.TrimStart('\n'));
        // Guarantee trailing newline so editors don't re-add one and break
        // byte-equality on the next regen.
        if (!sb.ToString().EndsWith('\n')) sb.Append('\n');
        return sb.ToString();
    }

    private static string FlattenForFrontmatter(string value) =>
        value.Replace("\r\n", " ").Replace("\n", " ").Replace("\r", " ").Trim();

    private static byte[]? BuildOrchestratorJsonBytes(DoxieSkillCanon skill)
    {
        var manifest = skill.Manifest;
        var hasContent = !string.IsNullOrWhiteSpace(manifest.DisplayName)
            || manifest.Category is not null
            || (manifest.Requirements?.Count ?? 0) > 0
            || (manifest.Modes?.Count ?? 0) > 0;
        if (!hasContent) return null;

        var sidecar = new
        {
            displayName = manifest.DisplayName,
            category = manifest.Category,
            requirements = manifest.Requirements,
            modes = manifest.Modes,
        };
        var json = JsonSerializer.Serialize(sidecar, OrchestratorJsonOptions);
        // Trailing newline for POSIX-friendly diff hygiene.
        return Encoding.UTF8.GetBytes(json + "\n");
    }

    private static void WriteIfChanged(string path, byte[] desired)
    {
        if (File.Exists(path))
        {
            var existing = File.ReadAllBytes(path);
            if (existing.Length == desired.Length && existing.AsSpan().SequenceEqual(desired))
            {
                return;
            }
        }
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllBytes(path, desired);
    }
}
